spring:
  application:
    name: product-search

# SOLR
solr:
  host: http://localhost:8983/solr
  
springdoc:
  api-docs.path: /api-docs
  
  
logging:
  level:
    org.springframework.data.solr.core.SolrTemplate: DEBUG